// Generated by the protocol buffer compiler.  DO NOT EDIT!
// clang-format off
// source: google/protobuf/wrappers.proto

#import "VPKGPBDescriptor.h"
#import "VPKGPBMessage.h"
#import "VPKGPBRootObject.h"

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - VPKGPBWrappersRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (VPKGPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c VPKGPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
VPKGPB_FINAL @interface VPKGPBWrappersRoot : VPKGPBRootObject
@end

#pragma mark - VPKGPBDoubleValue

typedef VPKGPB_ENUM(VPKGPBDoubleValue_FieldNumber) {
  VPKGPBDoubleValue_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `double`.
 *
 * The JSON representation for `DoubleValue` is JSON number.
 **/
VPKGPB_FINAL @interface VPKGPBDoubleValue : VPKGPBMessage

/** The double value. */
@property(nonatomic, readwrite) double value;

@end

#pragma mark - VPKGPBFloatValue

typedef VPKGPB_ENUM(VPKGPBFloatValue_FieldNumber) {
  VPKGPBFloatValue_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `float`.
 *
 * The JSON representation for `FloatValue` is JSON number.
 **/
VPKGPB_FINAL @interface VPKGPBFloatValue : VPKGPBMessage

/** The float value. */
@property(nonatomic, readwrite) float value;

@end

#pragma mark - VPKGPBInt64Value

typedef VPKGPB_ENUM(VPKGPBInt64Value_FieldNumber) {
  VPKGPBInt64Value_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `int64`.
 *
 * The JSON representation for `Int64Value` is JSON string.
 **/
VPKGPB_FINAL @interface VPKGPBInt64Value : VPKGPBMessage

/** The int64 value. */
@property(nonatomic, readwrite) int64_t value;

@end

#pragma mark - VPKGPBUInt64Value

typedef VPKGPB_ENUM(VPKGPBUInt64Value_FieldNumber) {
  VPKGPBUInt64Value_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `uint64`.
 *
 * The JSON representation for `UInt64Value` is JSON string.
 **/
VPKGPB_FINAL @interface VPKGPBUInt64Value : VPKGPBMessage

/** The uint64 value. */
@property(nonatomic, readwrite) uint64_t value;

@end

#pragma mark - VPKGPBInt32Value

typedef VPKGPB_ENUM(VPKGPBInt32Value_FieldNumber) {
  VPKGPBInt32Value_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `int32`.
 *
 * The JSON representation for `Int32Value` is JSON number.
 **/
VPKGPB_FINAL @interface VPKGPBInt32Value : VPKGPBMessage

/** The int32 value. */
@property(nonatomic, readwrite) int32_t value;

@end

#pragma mark - VPKGPBUInt32Value

typedef VPKGPB_ENUM(VPKGPBUInt32Value_FieldNumber) {
  VPKGPBUInt32Value_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `uint32`.
 *
 * The JSON representation for `UInt32Value` is JSON number.
 **/
VPKGPB_FINAL @interface VPKGPBUInt32Value : VPKGPBMessage

/** The uint32 value. */
@property(nonatomic, readwrite) uint32_t value;

@end

#pragma mark - VPKGPBBoolValue

typedef VPKGPB_ENUM(VPKGPBBoolValue_FieldNumber) {
  VPKGPBBoolValue_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `bool`.
 *
 * The JSON representation for `BoolValue` is JSON `true` and `false`.
 **/
VPKGPB_FINAL @interface VPKGPBBoolValue : VPKGPBMessage

/** The bool value. */
@property(nonatomic, readwrite) BOOL value;

@end

#pragma mark - VPKGPBStringValue

typedef VPKGPB_ENUM(VPKGPBStringValue_FieldNumber) {
  VPKGPBStringValue_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `string`.
 *
 * The JSON representation for `StringValue` is JSON string.
 **/
VPKGPB_FINAL @interface VPKGPBStringValue : VPKGPBMessage

/** The string value. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

@end

#pragma mark - VPKGPBBytesValue

typedef VPKGPB_ENUM(VPKGPBBytesValue_FieldNumber) {
  VPKGPBBytesValue_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `bytes`.
 *
 * The JSON representation for `BytesValue` is JSON string.
 **/
VPKGPB_FINAL @interface VPKGPBBytesValue : VPKGPBMessage

/** The bytes value. */
@property(nonatomic, readwrite, copy, null_resettable) NSData *value;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
